### PR TITLE
Refactor/remove render binds

### LINKED ISSUE #20: Should not bind in render
Functions bound in render get recreated during each render. Could pose a performance problem.

https://ryanfunduk.com/articles/never-bind-in-render/

### PR DESCRIPTION
**Pull request by Redmega**
resolves #20

@KyleAMathews Noticed you've been making changes in your fork and then doing pull requests over. Is that the proper way to commit as a contributor or is it personal preference?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
It doesn't matter too much for core collaborators if you're working off your own fork or a branch in the main repo as long as it only gets merged to master through a PR.

I've actually been just using Prettier to format the code as it goes beyond Eslint in a number of really nice ways — https://github.com/prettier/prettier

ESlint is definitely really nice but it doesn't do a great job at automatically formatting code which is the main thing I at least want from this sort of code.

I'd be fine with a minimal set of eslint rules that align with Prettier but otherwise, let's just not change formatting to match eslint's rules.

**Comment by KyleAMathews** [comment]
Also we're using Yarn to manage dependencies so please when you add or remove a package use the [Yarn equivalent commands](https://yarnpkg.com/en/docs/usage) to do so to ensure that the yarn.lock stays up to date.

**Comment by Redmega** [comment]
Can you cherrypick commits 925be8f and 4b2c502 then? That has the relevant changes for the binding. Else I'll do another pull request tomorrow.

**Comment by KyleAMathews** [comment]
Oh right, I thought it was just a stylistic PR. I'll just merge this and then re-run Prettier.

**Comment by KyleAMathews** [comment]
2.1.5 is out

**Comment by Redmega** [comment]
I'll install the `prettier` package in Atom and format on save from now on so I don't run into these issues anymore. I had been using eslint for the live linting as I noticed there was an `.eslintrc` file but I suppose that's a relic from stoeffel.

**Pull request merged**
