### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by KyleAMathews**
Hi! Great component — tried a bunch of react drawer components and this was my favorite. Loved use of react-motion (great for making responding to touch feel really natural vs. css). I'm using it on a client site (early preview https://electrician-tendency-11817.netlify.com/v12.0.0/guides/icons/) and make a few small fixes to get things working for server rendering plus updated dependencies.

I'll probably be using the component on a few more client sites so would be happy to be made a collaborator if you'd like some help!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmm... and not sure why the version in package.json got bumped — changing that back.

**Comment by KyleAMathews** [comment]
@stoeffel ping

**Comment by stoeffel** [comment]
@KyleAMathews I don't have time to maintain this anymore (see #14 ).
Are you interested in taking it over? Will add you to npm and the repo.

**Comment by KyleAMathews** [comment]
Would love to maintain it. I'm kyleamathews on github and kylemathews on
npm. Thanks for all the work you've put into it!

**Comment by stoeffel** [comment]
I added you! thanks ❤️

**Comment by KyleAMathews** [comment]
Published 2.1.2!

**Pull request merged**
