### PR TITLE
chore: bump dependencies to latest

### PR DESCRIPTION
**Pull request by Redmega**
I've bumped React up to 16. Because of this, I've updated the version to v3.0.0, as requiring React v16 might break applications still on v15.

Thoughts?

### CODE REVIEW

**Comment by Redmega** [comment]
@stoeffel Can you check what errors are there on netlify?

I would even say disable it for pull requests, only have it follow changes to `master`.

**Comment by Redmega** [comment]
I just realized the react version of the example won't affect the users... I'll roll back the version.

**Comment by Redmega** [comment]
Actually, I am confused as to why `react` doesn't need to be a dependency and is only a devDependency. I believe it should be added as a dependency with the version as `^15.4.2 || ^16.0.0`.

**Comment by Redmega** [comment]
Based on some research with my projects I am bumping the patch version instead of the major version after I add the peer dependencies. These peer dependencies should be backwards compatible.

@stoeffel if you could show me why the deploy preview failed that would be great, maybe I have some misconceptions which aren't accurate regarding updating the dependencies in this way.

**Comment by stoeffel** [comment]
@Redmega could you send me your email address? So I can add you as an admin on netlify?

**Comment by stoeffel** [comment]
You are now a admin on netlify.  @Redmega thanks for your contributions.

**Comment by Redmega** [comment]
Thanks @stoeffel!

Boiled it down to webpack config. The new webpack versions have different config requirements (duh!)

Almost done with that.

**Comment by Redmega** [comment]
My only concern now is that `"react-hammerjs": "^1.0.1"` might break (We were previously on `^0.5.0`).

**Pull request merged**
