### PR TITLE
don't allow dragging drawer anywhere on the screen

### PR DESCRIPTION
**Pull request by timurridjanovic**
#34

### CODE REVIEW

**Comment by Redmega** [comment]
Nice! Quick and easy fix. I'll test it out when I get home from work.

**Comment by timurridjanovic** [comment]
any updates on this?

**Comment by Redmega** [comment]
I had an emergency to handle at work, didn't get the chance to look at this. So sorry about that! I'm still pretty busy but I'll make my best effort to look at this by Wednesday. All I really want to do before I add it is to see it in action, so as soon as I get the chance to sit down I'll take care of it.

**Comment by Redmega** [comment]
Works great! @timurridjanovic thanks for the PR! Merging this in. I can't publish tonight, it's very late, but I'll get to it tomorrow.

**Pull request merged**
